#修改时注意不要破坏空格缩进,yaml不支持Tab键缩进，请使用同等长度空格缩进
name: mtshenquan-aciton
on:
  watch:
    types: started
  schedule:
    - cron: '0 3,9,13 * * *' #时间已换算，实际为11，17，21点,但github action 采取排队运行机制，可能导致您的定时计划延后，建议自行根据实际运行情况选择调整或推荐使用终端脚本
jobs:
  mt-action:
    name: my mt-action job
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: run meituanshenquan scripts
        env:
          serverkey: ${{ secrets.SERVERKEY }}     #必填项目,请自行在fork的项目上设置 秘密环境变量，变量含义：server 酱推送所用token
          pushPlusToken: ${{ secrets.PUSHPLUSTOKEN }} #必填项目,请自行在fork的项目上设置 秘密环境变量，变量含义：pushPlus推送所用token
          yesornot: "n" #必填项目,双引号内填写n则代表不开启server酱推送,填写n则开启推送
          yesornot2: "y" #必填项目,双引号内填写n则代表不开启pushPlus推送,填写n则开启推送
          webhook: "~"       #选填项目,变量含义：用于pushPlus 企业微信推等其他推送渠道所用，默认推送渠道无需设置注释即可
          #若需启用企业微信推送，请自行在fork的项目上设置 秘密环境变量webhook，并将上一行 "～" 覆盖成${{ secrets.webhook }} 并取消上一行注释，取消注释后注意空格缩进对齐
          token: ${{ secrets.MTTOKEN }}   #必填项目,请自行在fork的项目上设置 秘密环境变量，变量含义：美团token
          on: 1  #必填项目,此配置为默认开启在有十元必中符的情况下自动抢15以上红包，若需关闭，请将1改为0，注意勿破坏空格缩进
          left : 0   #必填项目,若在默认开启自动抢15以上红包且有10元以上必中符的情况下，无法抢到必中符保底红包，请手动将该值从0改大些
          wm_latitude: "30657401" #必填项目,此处双引号填写不带小数点的纬度,此处为成都纬度
          wm_longitude: "104063321" #必填项目,此处双引号填写不带小数点的经度，此处为成都经度
          propId: "5" #必填项目,此处双引号填写红包豆自动兑换的道具类型,5对应15元必中符，建议填写5即可
          exchangeCoinNumber: "1800" #必填项目,此处双引号填写兑换上一行必中符所需红包豆,建议填写1800即可
          setexchangedou: "1800" #必填项目,此处双引号填写当红包豆大于等于多少豆时才执行红包豆转必中符脚本,建议填写1800即可,脚本会在抢不到15元必中符时自动兑换8元必中符
        run: |
          python mt-action-scripts.py

 
    
